"""Changes reminder table

Revision ID: 9fac51c807d2
Revises: 9e82bf604fea
Create Date: 2025-01-28 12:10:55.667009

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9fac51c807d2"
down_revision: Union[str, None] = "9e82bf604fea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reminder", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("reminder", "creation_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder",
        sa.Column(
            "creation_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("reminder", "created_at")
    # ### end Alembic commands ###
