"""inventory item create

Revision ID: 1aec6638c2df
Revises: 25f0fd2b753f
Create Date: 2024-11-28 11:24:16.705466

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1aec6638c2df"
down_revision: Union[str, None] = "25f0fd2b753f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
