"""inventory item create

Revision ID: 25f0fd2b753f
Revises: 581d6326c67e
Create Date: 2024-11-28 11:15:03.797477

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "25f0fd2b753f"
down_revision: Union[str, None] = "581d6326c67e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
