"""Initial migration

Revision ID: 458165d4765f
Revises: 1aec6638c2df
Create Date: 2024-11-28 11:31:27.891114

"""

from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "458165d4765f"
down_revision: Union[str, None] = "1aec6638c2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
