"""Initial migration

Revision ID: abff64c4ac58
Revises: 458165d4765f
Create Date: 2024-11-28 11:47:29.362948

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "abff64c4ac58"
down_revision: Union[str, None] = "458165d4765f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
